package com.hm.vote.vo;



public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbadministrators.admin_id
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbadministrators.first_name
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbadministrators.last_name
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbadministrators.email
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbadministrators.password
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbadministrators.admin_id
     *
     * @return the value of tbadministrators.admin_id
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbadministrators.admin_id
     *
     * @param adminId the value for tbadministrators.admin_id
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbadministrators.first_name
     *
     * @return the value of tbadministrators.first_name
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbadministrators.first_name
     *
     * @param firstName the value for tbadministrators.first_name
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbadministrators.last_name
     *
     * @return the value of tbadministrators.last_name
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbadministrators.last_name
     *
     * @param lastName the value for tbadministrators.last_name
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbadministrators.email
     *
     * @return the value of tbadministrators.email
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbadministrators.email
     *
     * @param email the value for tbadministrators.email
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbadministrators.password
     *
     * @return the value of tbadministrators.password
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbadministrators.password
     *
     * @param password the value for tbadministrators.password
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }
}