package com.hm.vote.vo;

import java.util.Date;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpositions.position_id
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpositions.position_name
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpositions.create_date
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpositions.status
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpositions.position_id
     *
     * @return the value of tbpositions.position_id
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpositions.position_id
     *
     * @param positionId the value for tbpositions.position_id
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }
    
    public void setPositionId(String positionId) {
    	
        this.positionId = Integer.parseInt(positionId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpositions.position_name
     *
     * @return the value of tbpositions.position_name
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpositions.position_name
     *
     * @param positionName the value for tbpositions.position_name
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpositions.create_date
     *
     * @return the value of tbpositions.create_date
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpositions.create_date
     *
     * @param createDate the value for tbpositions.create_date
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpositions.status
     *
     * @return the value of tbpositions.status
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpositions.status
     *
     * @param status the value for tbpositions.status
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }
}