package com.hm.vote.mappers;

import com.hm.vote.vo.Admin;
import com.hm.vote.vo.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbadministrators
     *
     * @mbg.generated Sun Oct 03 15:05:30 GST 2021
     */
    int updateByPrimaryKey(Admin record);
}