package com.hm.vote.mappers;

import com.hm.vote.vo.Candidate;
import com.hm.vote.vo.CandidateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CandidateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	long countByExample(CandidateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int deleteByExample(CandidateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int deleteByPrimaryKey(Integer candidateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int insert(Candidate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int insertSelective(Candidate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	List<Candidate> selectByExample(CandidateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	Candidate selectByPrimaryKey(Integer candidateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int updateByExampleSelective(@Param("record") Candidate record, @Param("example") CandidateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int updateByExample(@Param("record") Candidate record, @Param("example") CandidateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int updateByPrimaryKeySelective(Candidate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbcandidates
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	int updateByPrimaryKey(Candidate record);
}