package com.hm.vote.mappers;

import com.hm.vote.vo.Position;
import com.hm.vote.vo.PositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    long countByExample(PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int deleteByExample(PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int deleteByPrimaryKey(Integer positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int insertSelective(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    List<Position> selectByExample(PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    Position selectByPrimaryKey(Integer positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int updateByExampleSelective(@Param("record") Position record, @Param("example") PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int updateByExample(@Param("record") Position record, @Param("example") PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int updateByPrimaryKeySelective(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpositions
     *
     * @mbg.generated Sun Oct 03 15:07:36 GST 2021
     */
    int updateByPrimaryKey(Position record);
}