package com.hm.vote.vo;

import java.util.Date;

public class Candidate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbcandidates.candidate_id
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	private Integer candidateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbcandidates.candidate_name
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	private String candidateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbcandidates.create_date
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbcandidates.status
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbcandidates.candidate_id
	 * @return  the value of tbcandidates.candidate_id
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public Integer getCandidateId() {
		return candidateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbcandidates.candidate_id
	 * @param candidateId  the value for tbcandidates.candidate_id
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public void setCandidateId(Integer candidateId) {
		this.candidateId = candidateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbcandidates.candidate_name
	 * @return  the value of tbcandidates.candidate_name
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public String getCandidateName() {
		return candidateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbcandidates.candidate_name
	 * @param candidateName  the value for tbcandidates.candidate_name
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public void setCandidateName(String candidateName) {
		this.candidateName = candidateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbcandidates.create_date
	 * @return  the value of tbcandidates.create_date
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbcandidates.create_date
	 * @param createDate  the value for tbcandidates.create_date
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbcandidates.status
	 * @return  the value of tbcandidates.status
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbcandidates.status
	 * @param status  the value for tbcandidates.status
	 * @mbg.generated  Mon Oct 04 17:41:20 GST 2021
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}